ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/iperf-$VER/bin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install libssl-dev libsctp-dev;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists;\
  fi;\
  [ "$(id -g none)" = "" ] && groupadd -g 666 none;\
  [ "$(id -u none)" = "" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  curl $DOPT $DURL/sw/opensource/iperf/bin/iperf-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv iperf-$VER iperf;\
  S=zlocal-iperf.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/101312-iperf/files/$S || echo Script $S not available;\
  ls -l /usr/local;\
  iperf3 -v;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
