ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/openssh-$VER/bin:$PATH

RUN set -ex;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  curl -sSL -f -k http://repo/sw/opensource/openssh/bin/openssh-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv openssh-$VER openssh;\
  chown -R root:root openssh-$VER;\
  mkdir -pv etc/ssh;\
  ls -l /usr/local;\
  ssh -Q kex;\
  ssh -Q key;\
  ssh -Q cipher;\
  ssh -Q mac;\
  ssh -V;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
