ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/bacula-$VER/bin:/usr/local/psql/bin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  mv -v /cmd.d/190-ep-supervisord.sh.disabled /cmd.d/190-ep-supervisord.sh;\
  if expr match $OSN centos || expr match $OSN rocky; then\
    yum -y update;\
    yum -y install lzo libpq;\
    yum clean all;\
  fi;\
  groupadd -g 26 postgres;\
  useradd -u 26 -g 26 -m -s /bin/bash postgres;\
  cd /usr/local;\
  V=$(curl -s $DURL/sw/opensource/pgsql/bin/version.txt | grep ^pgsql-18: | awk '{print $2}');\
  curl $DOPT $DURL/sw/opensource/pgsql/bin/pgsql-$V-$OSN-$OSA.tar.gz | tar xzf -;\
  chown -R root:root pgsql-$V;\
  ln -snfv pgsql-$V pgsql-${V%.*};\
  ln -snfv pgsql-${V%.*} psql;\
  echo "info.vers = pgsql/$V" >> /tmp/vers.txt;\
  curl $DOPT $DURL/sw/opensource/bacula/$VER/bin/bacula-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv bacula-$VER bacula;\
  mkdir -pv etc/bacula/bacula-dir.d;\
  chown root:root etc/bacula/bacula-dir.d;\
  chmod 0750 etc/bacula/bacula-dir.d;\
  mkdir -pv /var/opt/bacula /var/log/bacula;\
  S=zlocal-bacula.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001012-bacula/files/$S || echo Script $S not available;\
  ls -l /usr/local;\
  (bconsole -? || true) 2>&1 | grep -i version;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
  [ ! -f /tmp/vers.txt ] || (cat /tmp/vers.txt && rm -f /tmp/vers.txt);\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
COPY supervisord/supervisord-* /usr/local/etc/supervisord.d/
CMD ["/cmd.sh"]
