ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

RUN set -ex;\
  apt-get update;\
  DEBIAN_FRONTEND=noninteractive apt-get -yqq install cups cups-ipp-utils whois;\
  apt-get clean;\
  mkdir -p /usr/local/etc/cups;\
  useradd -G lp,lpadmin -m -p $(mkpasswd cups) cups;\
  apt policy cups;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM") > /version.d/version-$REPO.txt;

ADD config/cupsd.conf config/cups-files.conf /usr/local/etc/cups/

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
