ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/sonar-scanner-$VER/bin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  groupadd -g 435 sonarqube;\
  useradd -u 435 -g 435 -c "SonarQube" -m -s /bin/bash sonarqube;\
  cd /usr/local;\
  curl $DOPT -o /tmp/f.zip $DURL/sw/opensource/sonar-scanner/bin/sonar-scanner-cli-$VER.zip;\
  unzip -q /tmp/f.zip;\
  rm -fv /tmp/f.zip;\
  ln -snfv sonar-scanner-$VER sonar-scanner;\
  sonar-scanner --version;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
