ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/blackbox_exporter-$VER:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  mkdir -pv blackbox_exporter-$VER;\
  ln -snfv blackbox_exporter-$VER blackbox_exporter;\
  curl $DOPT $DURL/sw/opensource/prometheus/bin/blackbox_exporter-$VER.linux-amd64.tar.gz | tar xvzf - --strip-components=1 -C blackbox_exporter;\
  chown -R root:root blackbox_exporter-$VER;\
  mkdir -pv etc/blackbox_exporter;\
  ls -l /usr/local;\
  blackbox_exporter --version;

COPY config/ /usr/local/etc/blackbox_exporter/

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
