ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/alertmanager-$VER:$PATH

RUN set -ex;\
  [ "$(id -g none)" = "" ] && groupadd -g 666 none;\
  [ "$(id -u none)" = "" ] && useradd -u 666 -g 666 -s /bin/bash -m none;\
  cd /usr/local;\
  mkdir -pv alertmanager-$VER;\
  curl -sS -L -k -f http://repo/sw/opensource/prometheus/bin/alertmanager-$VER.linux-amd64.tar.gz | tar xvzf - --strip-components=1 -C alertmanager-$VER;\
  chown -R root:root /usr/local/alertmanager-$VER;\
  mkdir -pv /usr/local/etc/alertmanager /var/opt/alertmanager;\
  chown -R none:none /var/opt/alertmanager;\
  ln -snfv alertmanager-$VER alertmanager;\
  alertmanager --version;

ADD config/ /usr/local/etc/alertmanager/

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
