ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/freeradius-$VER/bin:/usr/local/freeradius-$VER/sbin:$PATH

RUN set -ex;\
  if [ "$(echo $OS_NAME|cut -c1-6)" = "debian" ]; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install libtalloc2;\
    apt-get clean;\
  elif [ "$(echo $OS_NAME|cut -c1-5)" = "rocky" ]; then\
    yum -y install libtalloc openldap;\
    yum clean all;\
  elif [ "$(echo $OS_NAME|cut -c1-6)" = "centos" ]; then\
    yum -y install libtalloc openldap;\
    yum clean all;\
  fi;\
  groupadd -g 95 radiusd;\
  useradd -u 95 -g 95 -m radiusd;\
  mkdir -pv /var/lib/radiusd /var/run/radiusd /var/log/radius/radacct;\
  chown -v radiusd:radiusd /var/lib/radiusd /var/run/radiusd /var/log/radius/radacct;\
  curl -sS -L -k -f http://repo/sw/opensource/freeradius/bin/freeradius-$VER-$OS_NAME-$OS_ARCH.tar.gz | tar xzf - -C /usr/local;\
  chown -R root:root /usr/local/freeradius-$VER;\
  cd /usr/local;\
  ln -snfv freeradius-$VER freeradius;\
  radiusd -v;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
