ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/guacamole-server-$VER/bin:/usr/local/guacamole-server-$VER/sbin:$PATH
ENV LD_LIBRARY_PATH /usr/local/guacamole-server/lib:/usr/local/ffmpeg/lib:/usr/local/libwebsockets/lib

STOPSIGNAL SIGKILL

RUN set -ex;\
  yum -y install uuid libwebp libssh2 freerdp libvncserver cairo pango numactl-libs;\
  yum -y install xorg-x11-fonts-* urw-base35-*;\
  yum clean all;\
  cd /usr/local;\
  V=$(curl -s http://repo/sw/opensource/ffmpeg/bin/version.txt | grep ^ffmpeg: | awk '{print $2}');\
  curl -sS -L -k -f http://repo/sw/opensource/ffmpeg/bin/ffmpeg-${V}-${OS_NAME}-${OS_ARCH}.tar.gz | tar xzf - -C /usr/local;\
  ln -snfv ffmpeg-${V} ffmpeg-${V%%.*};\
  ln -snfv ffmpeg-${V%%.*} ffmpeg;\
  V=$(curl -s http://repo/sw/opensource/libwebsockets/bin/version.txt | grep ^libwebsockets: | awk '{print $2}');\
  curl -sS -L -k -f http://repo/sw/opensource/libwebsockets/bin/libwebsockets-${V}-${OS_NAME}-${OS_ARCH}.tar.gz | tar xzf - -C /usr/local;\
  ln -snfv libwebsockets-${V} libwebsockets;\
  curl -sS -L -k -f http://repo/sw/opensource/apache-guacamole/bin/server/guacamole-server-${VER}-${OS_NAME}-${OS_ARCH}.tar.gz | tar xzf - -C /usr/local;\
  chown -R root:root /usr/local/guacamole-server-${VER};\
  ln -snfv guacamole-server-${VER} guacamole-server;\
  ln -snfv /usr/local/guacamole-server/usr/lib64/freerdp2/libguac-common-svc-client.so /usr/lib64/freerdp2;\
  ln -snfv /usr/local/guacamole-server/usr/lib64/freerdp2/libguacai-client.so /usr/lib64/freerdp2;\
  mkdir -pv /etc/guacamole;\
  guacd -v;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
