ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG TYPE
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

RUN set -ex;\
  cd /usr/local;\
  mkdir -pv phpldapadmin-$VER;\
  curl -sS -L -k -f http://repo/sw/opensource/phpldapadmin/phpLDAPadmin-$VER.tar.gz | tar xzf - -C phpldapadmin-$VER --strip-components=1;\
  ln -snfv phpldapadmin-$VER phpldapadmin;\
  mkdir -pv /usr/local/etc/phpldapadmin;\
  touch /usr/local/etc/phpldapadmin/config.php;\
  ln -snfv /usr/local/etc/phpldapadmin/config.php /usr/local/phpldapadmin/config/;\
  cat phpldapadmin/VERSION;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.type = ${TYPE:-[none]}";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
