ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /opt/local/erlang-$VER/bin:$PATH

RUN set -ex;\
  cd /opt/local;\
  curl -sS -L -k -f http://repo/sw/opensource/erlang/bin/erlang-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv erlang-$VER erlang;\
  chown -R root:root erlang-$VER;\
  ls -l /opt/local;\
  erl -noshell -eval 'erlang:display(erlang:system_info(system_version))' -eval 'init:stop()';

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
