ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/pgadmin4-$VER/bin:$PATH
ENV PGADMIN4_PGVERS "18 17 16"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  if expr match $OSN debian13; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install python3-distutils-extra;\
    apt-get -yqq install python3-virtualenv;\
    apt-get -yqq install libicu-dev;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists;\
  fi;\
  if expr match $OSN debian12; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install python3-distutils python3-lib2to3;\
    apt-get -yqq install python3-virtualenv;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
  fi;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  curl $DOPT $DURL/sw/opensource/pgadmin4/bin/pgadmin4-$VER-$OSN-venv.tar.gz | tar xzf -;\
  ln -snfv pgadmin4-$VER pgadmin4;\
  ln -snfv /usr/local/pgadmin4/bin/activate /usr/local/bin;\
  ln -snfv /usr/local/pgadmin4/bin/pgadmin4 /usr/local/bin;\
  ln -snfv /usr/local/pgadmin4/bin/pgadmin4-cli /usr/local/bin;\
  V=$(pip show gunicorn | grep -i ^version: | awk '{print $2}');\
  echo "info.vers = gunicorn/$V" >> /tmp/vers.txt;\
  mkdir -pv /var/opt/pgadmin4;\
  chown -Rv none:none /var/opt/pgadmin4;\
  S=$(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])');\
  mkdir -pv /usr/local/etc/pgadmin4;\
  ln -snfv /usr/local/etc/pgadmin4/config_local.py $S/pgadmin4/;\
  for V in $PGADMIN4_PGVERS; do\
    V=$(curl $DOPT $DURL/sw/opensource/pgsql/bin/version.txt|grep ^pgsql-$V:|tail -1|awk '{print $2}');\
    curl $DOPT $DURL/sw/opensource/pgsql/bin/pgsql-$V-$OSN-$OSA.tar.gz | tar xzf -;\
    [ -e pgsql-${V%.*} ] || ln -snfv pgsql-$V pgsql-${V%.*};\
    chown -R root:root pgsql-$V;\
  done;\
  ls -l /usr/local;\
  for V in $PGADMIN4_PGVERS; do\
    pgsql-$V/bin/postgres --version;\
  done;\
  pip show gunicorn;\
  pip show pgadmin4;

COPY config/config_local.py /usr/local/etc/pgadmin4/

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
  [ ! -f /tmp/vers.txt ] || (cat /tmp/vers.txt && rm -f /tmp/vers.txt);\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
