ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/opa-$VER:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  mkdir -pv etc/opa;\
  mkdir -pv opa-$VER;\
  ln -snfv opa-$VER opa;\
  cd opa;\
  curl $DOPT -O $DURL/sw/opensource/opa/bin/opa_linux_amd64_$VER;\
  ln -snfv opa_linux_amd64_$VER opa;\
  chmod a+x opa_linux_amd64_$VER;\
  ls -l /usr/local;\
  opa version;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
