ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/slurm-exporter-$VER:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  cd /usr/local;\
  mkdir -pv slurm-exporter-$VER;\
  ln -snfv slurm-exporter-$VER slurm-exporter;\
  curl $DOPT -o slurm-exporter/slurm-exporter $DURL/sw/opensource/prometheus/bin/slurm-exporter_${VER}_linux_amd64;\
  chown -R root:root slurm-exporter-$VER;\
  chmod a+x slurm-exporter/slurm-exporter;\
  slurm-exporter --version || true;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
