ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

RUN set -ex;\
  groupadd -g 701 gerrit;\
  useradd -u 701 -g 701 -m gerrit;\
  mkdir -pv /usr/local/gerrit;\
  cd /usr/local/gerrit;\
  curl -sS -L -k -f -o gerrit-${VER}.war http://repo/sw/opensource/gerrit/war/gerrit-$VER.war;\
  chown -R root:root gerrit-$VER.war;\
  ln -snfv gerrit-$VER.war gerrit.war;\
  mkdir -pv /var/opt/gerrit;\
  chown -R 0:0 /var/opt/gerrit;\
  chmod -R g=u /var/opt/gerrit;\
  java -jar /usr/local/gerrit/gerrit.war version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
