ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  groupadd -g 701 gerrit;\
  useradd -r -u 701 -g 701 -m -s /bin/bash gerrit;\
  cd /usr/local;\
  mkdir -pv gerrit-$VER;\
  ln -snfv gerrit-$VER gerrit;\
  cd gerrit;\
  curl $DOPT -o gerrit-$VER.war $DURL/sw/opensource/gerrit/war/gerrit-$VER.war;\
  ln -snfv gerrit-$VER.war gerrit.war;\
  chown -R root:root gerrit-$VER.war;\
  mkdir -pv /var/opt/gerrit;\
  chown -R 0:0 /var/opt/gerrit;\
  chmod -R g=u /var/opt/gerrit;\
  ls -l /usr/local;\
  java -jar gerrit.war version;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
