ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/prometheus-$VER:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  cd /usr/local;\
  mkdir -pv prometheus-$VER;\
  ln -snfv prometheus-$VER prometheus;\
  curl $DOPT $DURL/sw/opensource/prometheus/bin/prometheus-$VER.linux-amd64.tar.gz | tar xvzf - --strip-components=1 -C prometheus;\
  chown -R root:root prometheus-$VER;\
  mkdir -pv etc/prometheus;\
  mkdir -pv /var/opt/prometheus;\
  S=zlocal-prometheus.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/101403-prometheus/files/$S || echo Script $S not available;\
  ls -l /usr/local;\
  prometheus --version;

COPY config/ /usr/local/etc/prometheus/

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
