ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/ntfy-$VER:$PATH

RUN set -ex;\
  [ "$(id -g none)" = "" ] && groupadd -g 666 none;\
  [ "$(id -u none)" = "" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  mkdir -pv /var/opt/ntfy;\
  chown none:none /var/opt/ntfy;\
  mkdir -pv /usr/local/ntfy-$VER /etc/ntfy;\
  cd /usr/local;\
  curl -sS -L -k -f http://repo/sw/opensource/ntfy/bin/ntfy_${VER}_linux_amd64.tar.gz | tar xzf - --strip-components=1 -C ntfy-$VER;\
  chown -R root:root ntfy-$VER;\
  ln -snfv ntfy-$VER ntfy;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
