ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV LANG=en_US.utf8
ENV TZ=Europe/Warsaw
ENV OS_NAME=kali
ENV OS_ARCH=x86_64
ENV OS_CODE=kali-rolling

RUN set -ex;\
  if [ ! -z $APT_URL ]; then\
    echo "deb $APT_URL kali-rolling main contrib non-free" > /etc/apt/sources.list.d/kali-rolling.list;\
    echo 'Acquire::https::Verify-Peer "false";' > /etc/apt/apt.conf.d/99https-verify-peer;\
    echo 'Acquire::https::Verify-Host "false";' > /etc/apt/apt.conf.d/99https-verify-host;\
  fi;\
  export DEBIAN_FRONTEND=noninteractive;\
  apt-get update;\
  apt-get -yqq install jq vim xz-utils bsdextrautils;\
  apt-get clean;\
  wpscan --update;\
  cp -v /root/.bashrc /root/.bashrc.ORG;\
  cp -v /root/.bashrc.original /root/.bashrc;\
  S=zlocal-0001.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001900-kali/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-0002.bash;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001900-kali/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-0010.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001900-kali/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-ip.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001900-kali/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-searchsploit.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001200-pentests/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-apt.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001900-kali/files/$S\
    && (chmod a+rx /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-cdev-image.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/999210-cdev/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  cat /etc/os-release;\
  cat /etc/debian_version;

RUN set -ex;\
  mkdir -p /cmd.d /version.d;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.type = ${TYPE:-[none]}";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
ADD scripts/cmd.sh /
CMD ["/bin/bash","--login"]
