ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/rabbitmq-$VER/sbin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  cd /usr/local;\
  mkdir -pv rabbitmq-$VER;\
  ln -snfv rabbitmq-$VER rabbitmq;\
  curl $DOPT $DURL/sw/opensource/rabbitmq/bin/rabbitmq-server-generic-unix-$VER.tar.xz | tar xJf - --strip-components=1 -C rabbitmq;\
  chown -R root:root rabbitmq-$VER;\
  ls -l /usr/local;\
  rabbitmqctl version;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
