ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG TYPE
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV LANG=en_US.utf8
ENV TZ=Europe/Warsaw

ENV OS_NAME=rocky9
ENV OS_ARCH=x86_64

ENV OSN=rocky9
ENV OSA=x86_64

COPY config/rocky-$VER.repo /etc/yum.repos.d/

RUN set -eux;\
  cd /etc/yum.repos.d;\
  sed -i.b$(date +%y%m%d) 's/enabled=1/enabled=0/' ./*.repo;\
  rpm --import /etc/pki/rpm-gpg/*;\
  yum -y update;\
  yum -y --allowerasing install net-tools iproute nmap lsof strace telnet git curl wget bind-utils which unzip python3 python3-pip;\
  yum -y --allowerasing install coreutils procps-ng iputils glibc-langpack-en environment-modules;\
  yum -y --allowerasing install yum-utils createrepo tree;\
  yum clean all;\
  mkdir -pv /usr/local/etc/modulefiles;\
  S=zlocal-0001.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001580-rocky9/files/$S || echo Script $S not available;\
  S=zlocal-0002.bash;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001580-rocky9/files/$S || echo Script $S not available;\
  S=zlocal-0010.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001580-rocky9/files/$S || echo Script $S not available;\
  S=zlocal-ip.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001580-rocky9/files/$S || echo Script $S not available;\
  S=zlocal-process.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001580-rocky9/files/$S || echo Script $S not available;\
  S=zlocal-readme.bash;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001500-linux_admin/files/$S || echo Script $S not available;\
  mkdir -pv /usr/local/etc/doc;\
  S=zlocal-env-module.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001580-rocky9/files/$S || echo Script $S not available;\
  mkdir -pv /usr/local/etc/modulefiles;\
  mkdir -pv /opt/local/etc/modulefiles;\
  S=zlocal-cdev-image.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/999210-cdev/files/$S || echo Script $S not available;\
  groupadd -g 666 none;\
  useradd -u 666 -g 666 -s /bin/bash -m none;\
  cat /etc/redhat-release;

RUN set -eux;\
  pip3 install --no-index --trusted-host repo --find-links=$DURL/sw/opensource/python-modules/supervisor/ supervisor;\
  ln -sv /usr/local/etc/supervisord.conf /etc;\
  mkdir -pv /usr/local/etc/supervisord.d;\
  S=zlocal-supervisor.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/008330-supervisor/files/$S || echo Script $S not available;\
  supervisord --version;

COPY config/supervisord.conf /usr/local/etc

RUN set -eux;\
  curl $DOPT -o /tini $DURL/sw/opensource/tini/bin/tini-amd64-current;\
  chmod a+x /tini;\
  /tini --version;

RUN set -ex;\
  mkdir -pv /cmd.d /version.d;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.type = ${TYPE:-[none]}";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]* /cmd.d/
COPY scripts/cmd.sh /
