ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/acng-$VER/bin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install apt-cacher-ng;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists;\
  fi;\
  mkdir -pv /usr/local/etc/acng;\
  mkdir -pv /var/opt/acng/cache /var/opt/acng/log;\
  chown none:none /var/opt/acng/cache /var/opt/acng/log;\
  dpkg -l apt-cacher-ng;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY config/acng.conf /usr/local/etc/acng/
COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
