ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/ssldump-$VER/bin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install libnet1;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists;\
  fi;\
  cd /usr/local;\
  curl $DOPT $DURL/sw/opensource/ssldump/bin/ssldump-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv ssldump-$VER ssldump;\
  mkdir -pv /work;\
  ssldump -v;

WORKDIR /work

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
