ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

RUN set -ex;\
  export DEBIAN_FRONTEND=noninteractive;\
  apt-get update;\
  apt-get -yqq install minidlna;\
  apt-get clean;\
  groupadd -g 666 none;\
  useradd -u 666 -g 666 -m -s /bin/bash none;\
  mkdir -pv /usr/local/etc/minidlna;\
  mkdir -pv /var/opt/minidlna/music;\
  mkdir -pv /var/opt/minidlna/films;\
  mkdir -pv /var/opt/minidlna/photo;\
  minidlnad -V;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD config/*.conf /usr/local/etc/minidlna

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
