ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/unbound-$VER/sbin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  groupadd -g 891 unbound;\
  useradd -u 891 -g 891 -m -s /bin/bash unbound;\
  cd /usr/local;\
  curl $DOPT $DURL/sw/opensource/unbound/bin/unbound-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv unbound-$VER unbound-${VER%.*};\
  ls -l /usr/local;\
  unbound -V;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
