ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/opentofu-$VER:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  cd /usr/local;\
  mkdir -pv opentofu-$VER;\
  ln -snfv opentofu-$VER opentofu;\
  curl $DOPT -o /tmp/f.zip $DURL/sw/opensource/opentofu/bin/tofu_${VER}_linux_amd64.zip;\
  unzip -d opentofu /tmp/f.zip;\
  chown -R root:root opentofu-$VER;\
  mkdir -pv etc/opentofu;\
  V=$(curl -s $DURL/sw/opensource/opentofu/providers/version.txt | grep ^terraform-provider-libvirt: | tail -1 | awk '{print $2}');\
  mkdir -pv /usr/local/opentofu-providers/dc.local/local/libvirt;\
  cd /usr/local/opentofu-providers/dc.local/local/libvirt;\
  curl $DOPT -O $DURL/sw/opensource/opentofu/providers/terraform-provider-libvirt_${V}_linux_amd64.zip;\
  S=zlocal-opentofu.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/005020-opentofu/files/$S || echo Script $S not available;\
  ls -l /usr/local;\
  find /usr/local/opentofu-providers;\
  tofu version;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
  [ ! -f /tmp/vers.txt ] || (cat /tmp/vers.txt && rm -f /tmp/vers.txt);\
 ) > /version.d/version-$REPO.txt;
