ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/prosody-$VER/bin:$PATH

RUN set -ex;\
  export DEBIAN_FRONTEND=noninteractive;\
  apt-get update;\
  apt-get -yqq install lua5.2 liblua5.2-dev lua-expat lua-socket lua-filesystem lua-sec libidn11-dev libssl-dev;\
  apt-get -yqq install lua-ldap;\
  apt-get clean;\
  groupadd -g 821 prosody;\
  useradd -u 821 -g 821 -m -c "Prosody XMPP server" prosody;\
  mkdir -pv /var/opt/prosody /var/log/prosody;\
  chown prosody:prosody /var/opt/prosody /var/log/prosody;\
  cd /usr/local;\
  curl -sS -L -k -f http://repo/sw/opensource/prosody/bin/prosody-$VER-$OS_NAME-$OS_ARCH.tar.gz | tar xzf -;\
  ln -snfv prosody-$VER prosody;\
  mkdir -pv prosody-modules;\
  curl -sS -L -k -f http://repo/sw/opensource/prosody-modules/bin/prosody-modules.tar.gz | tar xzf - --strip-components=1 -C prosody-modules;\
  ln -snfv /usr/local/prosody-modules/mod_auth_ldap2/mod_auth_ldap2.lua /usr/local/prosody/lib/prosody/modules;\
  ln -snfv /usr/local/prosody-modules/mod_lib_ldap/ldap.lib.lua /usr/local/prosody/lib/prosody/modules;\
  ln -snfv /usr/local/prosody-modules/mod_storage_ldap/mod_storage_ldap.lua /usr/local/prosody/lib/prosody/modules;\
  ln -snfv /usr/local/prosody-modules/mod_storage_ldap/ldap /usr/local/prosody/lib/prosody/modules;\
  ln -snfv /usr/local/prosody-modules/mod_log_auth/mod_log_auth.lua /usr/local/prosody/lib/prosody/modules;\
  mkdir -pv /run/prosody;\
  chown prosody:prosody /run/prosody;\
  prosodyctl --config=/usr/local/prosody/etc/prosody/prosody.cfg.lua about;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
