ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  mkdir -pv jenkins-$VER;\
  ln -snfv jenkins-$VER jenkins;\
  curl $DOPT -o jenkins/jenkins-$VER.war $DURL/sw/opensource/jenkins/war/jenkins-$VER.war;\
  cd jenkins;\
  ln -snfv jenkins-$VER.war jenkins.war;\
  mkdir -pv /var/opt/jenkins;\
  chown -Rv none:none /var/opt/jenkins;\
  chmod -Rv g=u /var/opt/jenkins;\
  ls -l /usr/local;\
  java -jar jenkins.war --version;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
  [ ! -f /tmp/vers.txt ] || (cat /tmp/vers.txt && rm -f /tmp/vers.txt);\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
