ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

RUN set -ex;\
  groupadd -g 666 none;\
  useradd -u 666 -g 666 -m none;\
  cd /usr/local;\
  mkdir -pv jenkins-$VER;\
  ln -snfv jenkins-$VER jenkins;\
  curl -sS -L -k -f -o jenkins/jenkins-$VER.war http://repo/sw/opensource/jenkins/war/jenkins-$VER.war;\
  cd jenkins;\
  ln -snfv jenkins-$VER.war jenkins.war;\
  mkdir -pv /var/opt/jenkins;\
  chown -Rv none:none /var/opt/jenkins;\
  chmod -Rv g=u /var/opt/jenkins;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
  [ -f /tmp/vers.txt ] && (cat /tmp/vers.txt && rm -f /tmp/vers.txt) || true;\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
