ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV CATALINA_OPTS="-DJENKINS_HOME=/var/opt/jenkins -Djava.awt.headless=true"

COPY config/context.xml /var/opt/tomcat/conf/

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -ex;\
  curl $DOPT -o /as-apps/jenkins.war $DURL/sw/opensource/jenkins/war/jenkins-$VER.war;\
  mkdir -pv /var/opt/jenkins;\
  chown -R 0:0 /var/opt/jenkins;\
  chmod -R g=u /var/opt/jenkins;\
  ls -l /usr/local;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
