ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/httpd-$VER/bin:$PATH

RUN set -ex;\
  mv -v /cmd.d/190-ep-supervisord.sh.disabled /cmd.d/190-ep-supervisord.sh;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install libpcre2-dev liblua5.4-dev nettle-dev;\
    apt-get -yqq install libssl-dev libldap2-dev libxml2-dev libsqlite3-dev;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
  fi;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -r -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  curl -sSL -f -k http://repo/sw/opensource/apache-httpd/bin/httpd-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv httpd-$VER httpd;\
  chown -R root:root httpd-$VER;\
  mkdir -pv etc/httpd;\
  mkdir -pv /var/opt/httpd/html /var/opt/httpd/cgi-bin;\
  chown -R none:none /var/opt/httpd;\
  ln -snfv /var/opt/httpd/html /html;\
  ln -snfv /var/opt/httpd/cgi-bin /cgi-bin;\
  echo httpd-$INFO_VER > /html/index.html;\
  ls -l /usr/local;\
  httpd -V;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
ADD supervisord/supervisord-* /usr/local/etc/supervisord.d/
CMD ["/cmd.sh"]
