ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/openvpn-$VER/sbin:$PATH
ENV LD_LIBRARY_PATH /usr/local/openssl/lib64

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  mv -v /cmd.d/190-ep-supervisord.sh.disabled /cmd.d/190-ep-supervisord.sh;\
  if expr match $OSN centos; then\
    yum -y install lzo lz4;\
    yum clean all;\
  fi;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  V=$(curl -s $DURL/sw/opensource/openssl/bin/version.txt | grep ^openssl: | awk '{print $2}');\
  curl $DOPT $DURL/sw/opensource/openssl/bin/openssl-$V-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv openssl-$V openssl;\
  chown -R root:root openssl-$V;\
  curl $DOPT $DURL/sw/opensource/openvpn/bin/openvpn-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv openvpn-$VER openvpn;\
  chown -R root:root openvpn-$VER;\
  mkdir -pv /usr/local/etc/openvpn;\
  S=zlocal-openvpn.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/101050-openvpn/files/$S || echo Script $S not available;\
  /usr/local/openssl/bin/openssl version;\
  openvpn --version|fold -w 60 -s;

COPY scripts/openvpn-log.sh /usr/local/bin/

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
COPY supervisord/*.conf /usr/local/etc/supervisord.d/
CMD ["/cmd.sh"]
