ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/hostapd-$VER/bin:$PATH

#STOPSIGNAL SIGTERM

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install libssl-dev libnl-3-dev libnl-genl-3-dev;\
    apt-get -yqq install iw;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists;\
  fi;\
  cd /usr/local;\
  curl $DOPT $DURL/sw/opensource/hostapd/bin/hostapd-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv hostapd-$VER hostapd;\
  mkdir -pv etc/hostapd;\
  S=zlocal-wifi-iw.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/008400-wifi/files/$S || echo Script $S not available;\
  S=zlocal-hostapd.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/101700-hostapd/files/$S || echo Script $S not available;\
  ls -l /usr/local;\
  hostapd -v || true;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
