ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/ansible-$VER/bin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -ex;\
  cd /usr/local;\
  curl $DOPT $DURL/sw/opensource/ansible/bin/ansible-$VER-$OSN-venv.tar.gz | tar xzf -;\
  chown -R root:root ansible-$VER;\
  ln -snfv ansible-$VER ansible;\
  mkdir -pv /var/tmp/sw;\
  S=zlocal-ansible.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/101420-ansible/files/$S || echo Script $S not available;\
  S=zlocal-pkb.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/999030-work_pkb/files/$S || echo Script $S not available;\
  ls -l /usr/local;\
  which ansible-community && ansible-community --version;\
  ansible --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
