ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/rtsp2ws-$VER/bin:$PATH

RUN set -ex;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -r -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  mkdir -pv rtsp2ws-$VER;\
  ln -snfv rtsp2ws-$VER rtsp2ws;\
  curl -sS -L -k -f http://repo/sw/opensource/rtsp2ws/bin/rtsp2ws-v$VER-Linux-x86_64-Release.tar.gz | tar xzf - --strip-components=1 -C rtsp2ws;\
  chown -R root:root rtsp2ws-$VER;\
  mkdir -pv etc/rtsp2ws;\
  ls -l /usr/local;\
  rtsp2ws --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
