ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

RUN set -eux;\
  cd /usr/local;\
  mkdir -pv jenkins-plugin-manager;\
  cd jenkins-plugin-manager;\
  curl $DOPT -O $DURL/sw/opensource/jenkins/jar/jenkins-plugin-manager-$VER.jar;\
  ln -snfv jenkins-plugin-manager-$VER.jar jenkins-plugin-manager.jar;\
  mkdir -pv /work;\
  java -jar jenkins-plugin-manager.jar --version;

COPY scripts/*.sh /usr/local/bin
WORKDIR /work

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
