ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

RUN set -ex;\
  mkdir -pv /work;\
  mkdir -pv /usr/local/jenkins-plugin-manager;\
  cd /usr/local/jenkins-plugin-manager;\
  curl -sS -L -k -f -O http://repo/sw/opensource/jenkins/jar/jenkins-plugin-manager-$VER.jar;\
  ln -snfv jenkins-plugin-manager-$VER.jar jenkins-plugin-manager.jar;\
  java -jar /usr/local/jenkins-plugin-manager/jenkins-plugin-manager.jar --version;

ADD scripts/*.sh /usr/local/bin
WORKDIR /work

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
