ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

ADD config/context.xml /var/opt/tomcat/conf/

RUN set -ex;\
  if [ "$(echo $OS_NAME|cut -b 1-6)" = "debian" ]; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install graphviz;\
    apt-get clean;\
  elif [ "$(echo $OS_NAME|cut -b 1-6)" = "centos" ]; then\
    yum -y install graphviz;\
    yum clean all;\
  fi;\
  curl -sS -L -k -f -o /as-apps/plantuml.war http://repo/sw/opensource/plantuml/war/plantuml-$VER.war;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
