ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

COPY config/context.xml /var/opt/tomcat/conf/

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install graphviz;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists;\
  fi;\
  if expr match $OSN centos; then\
    yum -y install graphviz;\
    yum clean all;\
  fi;\
  curl $DOPT -o /as-apps/plantuml.war $DURL/sw/opensource/plantuml/war/plantuml-$VER.war;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
