ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/minio-$VER:$PATH

RUN set -ex;\
  groupadd -g 666 none;\
  useradd -u 666 -g 666 -m none;\
  mkdir -pv /var/opt/minio/main;\
  chown none:none /var/opt/minio/main;\
  cd /usr/local;\
  mkdir -pv minio-${VER};\
  curl -sS -L -k -f -o minio-$VER/minio http://repo/sw/opensource/minio/bin/minio-$VER;\
  curl -sS -L -k -f -o minio-$VER/mc http://repo/sw/opensource/minio/bin/mc;\
  chmod a+x minio-$VER/m*;\
  ln -snfv minio-$VER minio;\
  minio --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
