ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG TYPE
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV LANG=en_US.utf8
ENV TZ=Europe/Warsaw

ENV OS_NAME=centos7
ENV OS_ARCH=x86_64

ENV OSN=centos7
ENV OSA=x86_64

COPY config/centos-$VER.repo /etc/yum.repos.d/

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  yum-config-manager --disable '*' > /dev/null;\
  yum-config-manager --enable everything-$VER,updates-$VER > /dev/null;\
  rpm --import /etc/pki/rpm-gpg/*;\
  yum -y update;\
  yum -y install net-tools iproute nmap lsof strace telnet git curl wget bind-utils which unzip python-setuptools;\
  yum clean all;\
  S=zlocal-0001.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001540-centos7/files/$S || echo Script $S not available;\
  S=zlocal-0002.bash;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001540-centos7/files/$S || echo Script $S not available;\
  S=zlocal-0010.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001540-centos7/files/$S || echo Script $S not available;\
  S=zlocal-ip.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001540-centos7/files/$S || echo Script $S not available;\
  S=zlocal-process.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001540-centos7/files/$S || echo Script $S not available;\
  S=zlocal-readme.bash;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/001500-linux_admin/files/$S || echo Script $S not available;\
  mkdir -pv /usr/local/etc/doc;\
  S=zlocal-cdev-image.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/999210-cdev/files/$S || echo Script $S not available;\
  cat /etc/redhat-release;

RUN set -eux;\
  curl $DOPT $DURL/sw/opensource/python-modules/pip.tar.gz | tar xzf - -C /tmp;\
  python /tmp/pip/$(ls /tmp/pip|grep py2.py3|head -1)/pip install --no-index --find-links=/tmp/pip --upgrade pip;\
  rm -rf /tmp/pip;\
  pip install --no-index --trusted-host repo --find-links=http://repo/sw/opensource/python-modules/supervisor/ supervisor;\
  ln -sv /usr/local/etc/supervisord.conf /etc;\
  mkdir -pv /usr/local/etc/supervisord.d;\
  S=zlocal-supervisor.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/008330-supervisor/files/$S || echo Script $S not available;\
  supervisord --version;

COPY config/supervisord.conf /usr/local/etc

RUN set -eux;\
  curl $DOPT -o /tini $DURL/sw/opensource/tini/bin/tini-amd64-current;\
  chmod a+x /tini;\
  /tini --version;

RUN set -eux;\
  mkdir -pv /cmd.d /version.d;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.type = ${TYPE:-[none]}";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]* /cmd.d/
COPY scripts/cmd.sh /
