ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG TYPE
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/php-$VER/bin:/usr/local/php-$VER/sbin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  yum -y install postgresql-libs libpng libjpeg-turbo freetype libicu net-snmp-libs;\
  yum -y install http://repo/sw/linux/centos/epel/7/oniguruma-6.8.2-1.el7.x86_64.rpm;\
  yum clean all;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  V=$(curl -s $DURL/sw/opensource/fcgi/bin/version.txt | grep ^fcgi: | tail -1 | awk '{print $2}');\
  curl $DOPT $DURL/sw/opensource/fcgi/bin/fcgi-$V-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv fcgi-$V fcgi;\
  echo "info.vers = fcgi/$V" >> /tmp/vers.txt;\
  V=${VER%%.*};\
  curl $DOPT $DURL/sw/opensource/php/bin/php-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv php-$VER php-$V;\
  ln -snfv php-$V php;\
  cd etc;\
  ln -snfv php$V php;\
  cp -v php/php.ini-production php/php.ini;\
  mkdir -pv php/php-fpm.d;\
  S=zlocal-php-fpm.sh;\
  curl $DOPT -o /etc/profile.d/$S $DURL/pkb/pb/playbooks/101600-php/files/$S || echo Script $S not available;\
  ls -l /usr/local;\
  php --version;

COPY config/ /usr/local/etc/php/

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.type = ${TYPE:-[none]}";\
  echo "info.from = $FROM";\
  [ ! -f /tmp/vers.txt ] || (cat /tmp/vers.txt && rm -f /tmp/vers.txt);\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
COPY supervisord/supervisord-* /usr/local/etc/supervisord.d/
