ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/chartmuseum-$VER:$PATH

RUN set -ex;\
  [ "$(id -g none)" = "" ] && groupadd -g 666 none;\
  [ "$(id -u none)" = "" ] && useradd -u 666 -g 666 -s /bin/bash -m none;\
  cd /usr/local;\
  mkdir -pv chartmuseum-$VER;\
  curl -sS -L -k -f http://repo/sw/opensource/chartmuseum/bin/chartmuseum-v$VER-linux-amd64.tar.gz | tar xzf - --strip-components=1 -C chartmuseum-$VER;\
  chown -R root:root chartmuseum-$VER;\
  mkdir -pv /usr/local/etc/chartmuseum /var/opt/chartmuseum;\
  chown none:none /var/opt/chartmuseum;\
  ln -snfv chartmuseum-$VER chartmuseum;\
  chartmuseum --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD config/ /usr/local/etc/chartmuseum/
ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
