ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER
ARG DURL
ARG DOPT

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/jetty-$VER/bin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux;\
  groupadd -g 461 jetty;\
  useradd -u 461 -g 461 -c "Jetty Application Server" -m -s /bin/bash jetty;\
  cd /usr/local;\
  mkdir -pv jetty-$VER;\
  ln -snfv jetty-$VER jetty;\
  curl $DOPT $DURL/sw/opensource/jetty/bin/jetty-home-$VER.tar.gz | tar xzf - --strip-components=1 -C jetty;\
  chown -R root:jetty jetty-$VER;

RUN set -eux;\
  mkdir -pv /var/opt/jetty/default;\
  cd /var/opt/jetty/default;\
  if expr match $VER 12; then\
    java -jar /usr/local/jetty/start.jar --create-startd --add-modules=server,http,ee10-deploy,ee10-jsp,ext,resources;\
  else\
    java -jar /usr/local/jetty/start.jar --create-startd --add-to-start=server,http,deploy,jsp,jstl,ext,resources,websocket;\
  fi;\
  mkdir -pv webapps/ROOT;\
  echo \<%= \"jetty $VER\" %\> > webapps/ROOT/index.jsp;\
  chown -R jetty:root /var/opt/jetty/default;\
  ln -sv /var/opt/jetty/default/webapps/ROOT /as-root;\
  ln -sv /var/opt/jetty/default/webapps /as-apps;\
  mkdir -pv /var/opt/tomcat/conf;\
  sed -i.b$(date +%y%m%d) 's|> /dev/null &||' /usr/local/jetty/bin/jetty.sh;

RUN set -eux;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

COPY scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
